In [7]:
import numpy as np
import pandas as pd

In [8]:
df = pd.read_csv("earthquakes.csv")

In [9]:
df.head()

,Magnitude,UTC_Date_Time,Latitude,Longitude,Depth,Region,Hazard_Level
0,5.8,2025/10/24 16:40:10,43.004,145.638,42.0,"HOKKAIDO, JAPAN REGION",0
1,6.0,2025/10/13 11:11:00,7.248,141.605,10.0,"W. CAROLINE ISLANDS, MICRONESIA",1
2,5.8,2025/10/12 17:05:59,10.946,123.938,11.0,"CEBU, PHILIPPINES",0
3,7.7,2025/10/10 20:29:20,-60.174,-61.967,15.0,DRAKE PASSAGE,2
4,6.9,2025/10/10 11:12:07,7.172,126.755,48.0,"MINDANAO, PHILIPPINES",1

In [10]:
df.drop(columns=['UTC_Date_Time','Region'],inplace=True)

In [11]:
df.head()

   Magnitude  Latitude  Longitude  Depth  Hazard_Level
0        5.8    43.004    145.638   42.0             0
1        6.0     7.248    141.605   10.0             1
2        5.8    10.946    123.938   11.0             0
3        7.7   -60.174    -61.967   15.0             2
4        6.9     7.172    126.755   48.0             1

In [12]:
df.to_csv('Final_data.csv',index=False)